// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /policy-rules/{ruleId}"
  | "GET /claims"
  | "GET /me/claims"
  | "GET /me/team/claims"
  | "GET /policy-rules"
  | "PATCH /policy-rules/{ruleId}"
  | "POST /claims/{claimId}/decision"
  | "POST /me/claims"
  | "POST /me/claims/policy-check"
  | "POST /policy-rules";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /policy-rules/{ruleId}": { kind: "scope", scope: "policy-rules:manage" },
  "GET /claims": { kind: "scope", scope: "claims:read-all" },
  "GET /me/claims": { kind: "scope", scope: "claims:read" },
  "GET /me/team/claims": { kind: "scope", scope: "claims:read-team" },
  "GET /policy-rules": { kind: "scope", scope: "policy-rules:read" },
  "PATCH /policy-rules/{ruleId}": { kind: "scope", scope: "policy-rules:manage" },
  "POST /claims/{claimId}/decision": { kind: "scope", scope: "claims:decide" },
  "POST /me/claims": { kind: "scope", scope: "claims:submit" },
  "POST /me/claims/policy-check": { kind: "scope", scope: "claims:submit" },
  "POST /policy-rules": { kind: "scope", scope: "policy-rules:manage" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
