// Generated by the Ballerina OpenAPI tool from ../specs/design/components/expense-api/openapi.yaml,
// then hand-filled: the gateway has already enforced each operation's scope
// (see gateway_assertion.bal), so every handler below only resolves WHICH
// rows the caller may reach, per api-management/openapi-conventions.

import ballerina/http;
import ballerina/sql;
import ballerina/time;
import ballerina/uuid;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    // Every claim, across every team (Finance/Admin only — claims:read-all).
    // Reach is the path: no /me/ prefix, so no caller identity is read here.
    resource function get claims("submitted"|"approved"|"rejected"? status, string? employeeId,
            int 'limit = 20, int offset = 0) returns inline_response_200|error {
        sql:ParameterizedQuery whereClause = buildClaimsWhere(employeeId, status);
        int count = check countClaims(whereClause);
        ClaimRow[] rows = check queryClaimRows(whereClause, 'limit, offset);
        Claim[] claims = [];
        foreach ClaimRow row in rows {
            Claim claim = check assembleClaim(row);
            claims.push(claim);
        }
        [string?, string?] [next, previous] = paginationLinks("/claims", 'limit, offset, count);
        inline_response_200 result = { count, next, previous, data: claims };
        return result;
    }

    // The caller's own claims, resolved through the gateway assertion's sub.
    resource function get me/claims(http:RequestContext ctx, "submitted"|"approved"|"rejected"? status,
            int 'limit = 20, int offset = 0) returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorized("no verified caller on this request");
        }
        GatewayCaller caller = callerResult;
        sql:ParameterizedQuery whereClause = buildClaimsWhere(caller.userId, status);
        int count = check countClaims(whereClause);
        ClaimRow[] rows = check queryClaimRows(whereClause, 'limit, offset);
        Claim[] claims = [];
        foreach ClaimRow row in rows {
            Claim claim = check assembleClaim(row);
            claims.push(claim);
        }
        [string?, string?] [next, previous] = paginationLinks("/me/claims", 'limit, offset, count);
        inline_response_200 result = { count, next, previous, data: claims };
        return result;
    }

    // Create and send a claim, checked against policy on submit. The
    // Employee row is created here on first write when it does not already
    // exist — see employee_store.bal's ensureEmployee doc comment.
    resource function post me/claims(http:RequestContext ctx, @http:Payload ClaimInput payload)
            returns Claim|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorized("no verified caller on this request");
        }
        GatewayCaller caller = callerResult;
        if payload.total <= 0d {
            return badRequest("total must be greater than zero");
        }
        check ensureEmployee(caller.userId);
        string submittedAt = time:utcToString(time:utcNow());
        Claim created = check createClaim(caller.userId, payload, submittedAt);
        // The claim is already persisted at this point, so it must be
        // excluded from "other claims" here — evaluatePolicy adds `total`
        // back in itself, and counting the same row twice would double it.
        PolicyFlag[] policyFlags = check evaluatePolicy(caller.userId, payload.category, payload.claimDate,
            payload.total, created.id);
        Flag[] flags = [];
        foreach PolicyFlag pf in policyFlags {
            Flag flag = check insertFlag(created.id, pf.ruleId, pf.reason);
            flags.push(flag);
        }
        created.flags = flags;
        return created;
    }

    // Whether a draft claim would break a policy rule, before submitting.
    // Runs the same evaluatePolicy logic as submitClaim, against nothing but
    // this employee's already-persisted claims — this draft is never stored.
    resource function post me/claims/policy\-check(http:RequestContext ctx, @http:Payload PolicyCheckInput payload)
            returns PolicyCheckResultOk|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorized("no verified caller on this request");
        }
        GatewayCaller caller = callerResult;
        if payload.total <= 0d {
            return badRequest("total must be greater than zero");
        }
        PolicyFlag[] policyFlags = check evaluatePolicy(caller.userId, payload.category, payload.claimDate,
            payload.total, ());
        Flag[] flags = from PolicyFlag pf in policyFlags
            select { id: uuid:createRandomUuid(), ruleId: pf.ruleId, reason: pf.reason };
        PolicyCheckResultOk result = { body: { flags } };
        return result;
    }

    // Pending claims of the caller's own team — employees whose managerId is
    // the caller's own sub. See employee_store.bal: nothing in this API ever
    // sets managerId, so this is correct code over data that is always empty
    // today.
    resource function get me/team/claims(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorized("no verified caller on this request");
        }
        GatewayCaller caller = callerResult;
        string[] reportIds = check reportIdsOf(caller.userId);
        int count = check countTeamPendingClaims(reportIds);
        ClaimRow[] rows = check queryTeamPendingClaimRows(reportIds, 'limit, offset);
        Claim[] claims = [];
        foreach ClaimRow row in rows {
            Claim claim = check assembleClaim(row);
            claims.push(claim);
        }
        [string?, string?] [next, previous] = paginationLinks("/me/team/claims", 'limit, offset, count);
        inline_response_200 result = { count, next, previous, data: claims };
        return result;
    }

    // Approve or reject a submitted claim. A claim outside the caller's own
    // team — including one that does not exist at all — is 404, never 403.
    resource function post claims/[string claimId]/decision(http:RequestContext ctx, @http:Payload DecisionInput payload)
            returns ClaimOk|ErrorBadRequest|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized callerResult = requireGatewayCaller(ctx);
        if callerResult is http:Unauthorized {
            return unauthorized("no verified caller on this request");
        }
        GatewayCaller caller = callerResult;
        Claim? claim = check getClaimById(claimId);
        if claim is () {
            return notFound("no such claim in your reach");
        }
        string? claimEmployeeId = claim?.employeeId;
        if claimEmployeeId is () {
            return notFound("no such claim in your reach");
        }
        boolean ownsClaim = check isReportOfManager(claimEmployeeId, caller.userId);
        if !ownsClaim {
            return notFound("no such claim in your reach");
        }
        if claim.status != "submitted" {
            return badRequest("this claim was already decided");
        }
        string decidedAt = time:utcToString(time:utcNow());
        check insertDecision(claimId, caller.userId, payload.outcome, payload.comment, decidedAt);
        check markClaimDecided(claimId, payload.outcome);
        Claim? updated = check getClaimById(claimId);
        if updated is () {
            return notFound("no such claim in your reach");
        }
        ClaimOk result = { body: updated };
        return result;
    }

    // The active policy rules.
    resource function get policy\-rules() returns inline_response_200_1|ErrorUnauthorized|error {
        PolicyRule[] rules = check listActivePolicyRules();
        inline_response_200_1 result = { count: rules.length(), next: (), previous: (), data: rules };
        return result;
    }

    // Add a policy rule (Finance/Admin only — policy-rules:manage).
    resource function post policy\-rules(@http:Payload PolicyRuleInput payload)
            returns PolicyRule|ErrorBadRequest|ErrorUnauthorized|error {
        if payload.monthlyCapAmount <= 0d {
            return badRequest("monthlyCapAmount must be greater than zero");
        }
        PolicyRule created = check createPolicyRuleRow(payload);
        return created;
    }

    // Change or deactivate a policy rule.
    resource function patch policy\-rules/[string ruleId](@http:Payload PolicyRuleInput payload)
            returns PolicyRule|ErrorBadRequest|ErrorNotFound|ErrorUnauthorized|error {
        if payload.monthlyCapAmount <= 0d {
            return badRequest("monthlyCapAmount must be greater than zero");
        }
        PolicyRule? updated = check updatePolicyRuleRow(ruleId, payload);
        if updated is () {
            return notFound("no such policy rule");
        }
        return updated;
    }

    // Remove a policy rule.
    resource function delete policy\-rules/[string ruleId]() returns http:NoContent|ErrorNotFound|ErrorUnauthorized|error {
        boolean removed = check deletePolicyRuleRow(ruleId);
        if !removed {
            return notFound("no such policy rule");
        }
        return http:NO_CONTENT;
    }
}

public type DecisionInput record {
    "approved"|"rejected" outcome;
    string comment;
};

public type PolicyCheckResult record {
    # empty when the draft breaks no policy rule
    Flag[] flags;
};

public type PolicyRule record {
    string id;
    "meals"|"travel"|"accommodation"|"office-supplies"|"other" category;
    decimal monthlyCapAmount;
    string description?;
    boolean active = true;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type Flag record {
    string id;
    string ruleId;
    # plain-language reason the claim broke the rule
    string reason;
};

public type ClaimOk record {|
    *http:Ok;
    Claim body;
|};

public type Decision record {
    "approved"|"rejected" outcome;
    string comment;
    string managerId?;
    string decidedAt;
};

public type PolicyCheckInput record {
    string claimDate;
    decimal total;
    "meals"|"travel"|"accommodation"|"office-supplies"|"other" category;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type PolicyRuleInput record {
    "meals"|"travel"|"accommodation"|"office-supplies"|"other" category;
    decimal monthlyCapAmount;
    string description?;
    boolean active = true;
};

public type inline_response_200_1 record {
    int count;
    string? next?;
    string? previous?;
    PolicyRule[] data;
};

public type inline_response_200 record {
    int count;
    string? next?;
    string? previous?;
    Claim[] data;
};

public type PolicyCheckResultOk record {|
    *http:Ok;
    PolicyCheckResult body;
|};

public type Claim record {
    string id;
    string merchant;
    string claimDate;
    decimal total;
    string currency = "LKR";
    "meals"|"travel"|"accommodation"|"office-supplies"|"other" category;
    string note?;
    "submitted"|"approved"|"rejected" status;
    string employeeId?;
    string submittedAt?;
    Flag[] flags?;
    Decision decision?;
};

public type ClaimInput record {
    string merchant;
    string claimDate;
    decimal total;
    string currency = "LKR";
    "meals"|"travel"|"accommodation"|"office-supplies"|"other" category;
    string note?;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
